In [1]:
import torch
import torch.nn.functional as F

# Toy sentence embeddings (5 tokens, embedding dim = 4)
torch.manual_seed(42)
embeddings = torch.randn(5, 4)

# Create Query, Key, Value matrices
W_q = torch.randn(4, 4)
W_k = torch.randn(4, 4)
W_v = torch.randn(4, 4)

Q = embeddings @ W_q
K = embeddings @ W_k
V = embeddings @ W_v

# Scaled Dot-Product Attention
scores = Q @ K.T / (K.size(-1) ** 0.5)
attention_weights = F.softmax(scores, dim=-1)

output = attention_weights @ V

print("Attention Scores (before softmax):")
print(scores)

print("\nAttention Weights (after softmax):")
print(attention_weights)

print("\nFinal Attention Output:")
print(output)

Attention Scores (before softmax):
tensor([[  6.3643, -14.4820,   2.7980,  -2.6034,  -3.1163],
        [  0.6645,  10.4229,  -1.4408,   1.6973,   1.1837],
        [ -1.5968,   0.5730,  -0.4553,   0.1491,   0.2386],
        [ -0.7055,   4.4145,  -1.2577,   0.6804,   0.5363],
        [ -0.7732,  -0.7392,   1.7825,   0.1589,   0.5238]])

Attention Weights (after softmax):
tensor([[9.7232e-01, 8.5972e-10, 2.7478e-02, 1.2393e-04, 7.4202e-05],
        [5.7788e-05, 9.9968e-01, 7.0395e-06, 1.6232e-04, 9.7124e-05],
        [4.0179e-02, 3.5187e-01, 1.2583e-01, 2.3029e-01, 2.5183e-01],
        [5.6700e-03, 9.4877e-01, 3.2641e-03, 2.2670e-02, 1.9629e-02],
        [4.7366e-02, 4.9003e-02, 6.1006e-01, 1.2029e-01, 1.7328e-01]])

Final Attention Output:
tensor([[-4.3861e+00, -1.3294e+00, -3.6930e+00,  6.2093e-01],
        [ 5.0820e+00,  4.8930e-01, -1.1088e+00, -9.5282e-01],
        [ 1.8010e+00,  6.6467e-02, -6.4190e-01, -4.2525e-01],
        [ 4.8204e+00,  4.5406e-01, -1.0825e+00, -9.1517e-01],
    